"""initial schema

Revision ID: f6d9d6f5fbdf
Revises: 
Create Date: 2026-07-02 22:08:46.125717

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'f6d9d6f5fbdf'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_settings',
    sa.Column('key', sa.String(length=80), nullable=False),
    sa.Column('value_json', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('app_settings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_app_settings_key'), ['key'], unique=True)

    op.create_table('embedding_config',
    sa.Column('model', sa.String(length=120), nullable=False),
    sa.Column('dim', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('srd_entries',
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('data_json', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kind', 'slug')
    )
    with op.batch_alter_table('srd_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_srd_entries_kind'), ['kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_srd_entries_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_srd_entries_slug'), ['slug'], unique=False)

    op.create_table('users',
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('display_name', sa.String(length=80), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('campaigns',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('owner_id', sa.String(length=32), nullable=False),
    sa.Column('invite_code', sa.String(length=24), nullable=False),
    sa.Column('settings_json', sa.JSON(), nullable=False),
    sa.Column('world_clock', sa.String(length=120), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('campaigns', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_campaigns_invite_code'), ['invite_code'], unique=True)
        batch_op.create_index(batch_op.f('ix_campaigns_owner_id'), ['owner_id'], unique=False)

    op.create_table('campaign_members',
    sa.Column('campaign_id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('role', sa.String(length=10), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('campaign_id', 'user_id')
    )
    with op.batch_alter_table('campaign_members', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_campaign_members_campaign_id'), ['campaign_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_campaign_members_user_id'), ['user_id'], unique=False)

    op.create_table('characters',
    sa.Column('campaign_id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('race', sa.String(length=60), nullable=False),
    sa.Column('klass', sa.String(length=60), nullable=False),
    sa.Column('background', sa.String(length=60), nullable=False),
    sa.Column('alignment', sa.String(length=40), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('xp', sa.Integer(), nullable=False),
    sa.Column('hp_current', sa.Integer(), nullable=False),
    sa.Column('hp_max', sa.Integer(), nullable=False),
    sa.Column('hp_temp', sa.Integer(), nullable=False),
    sa.Column('ac', sa.Integer(), nullable=False),
    sa.Column('ability_scores_json', sa.JSON(), nullable=False),
    sa.Column('proficiencies_json', sa.JSON(), nullable=False),
    sa.Column('spell_slots_json', sa.JSON(), nullable=False),
    sa.Column('resources_json', sa.JSON(), nullable=False),
    sa.Column('conditions_json', sa.JSON(), nullable=False),
    sa.Column('death_saves_json', sa.JSON(), nullable=False),
    sa.Column('currency_json', sa.JSON(), nullable=False),
    sa.Column('sheet_json', sa.JSON(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_characters_campaign_id'), ['campaign_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_characters_user_id'), ['user_id'], unique=False)

    op.create_table('documents',
    sa.Column('campaign_id', sa.String(length=32), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('page_count', sa.Integer(), nullable=False),
    sa.Column('chunk_count', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=False),
    sa.Column('uploaded_by', sa.String(length=32), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_documents_campaign_id'), ['campaign_id'], unique=False)

    op.create_table('factions',
    sa.Column('campaign_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('goals', sa.Text(), nullable=False),
    sa.Column('dm_notes', sa.Text(), nullable=False),
    sa.Column('relationships_json', sa.JSON(), nullable=False),
    sa.Column('created_by', sa.String(length=10), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('factions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_factions_campaign_id'), ['campaign_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_factions_name'), ['name'], unique=False)

    op.create_table('items',
    sa.Column('campaign_id', sa.String(length=32), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('item_type', sa.String(length=60), nullable=False),
    sa.Column('rarity', sa.String(length=30), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('properties_json', sa.JSON(), nullable=False),
    sa.Column('source', sa.String(length=10), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_items_campaign_id'), ['campaign_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_items_name'), ['name'], unique=False)

    op.create_table('locations',
    sa.Column('campaign_id', sa.String(length=32), nullable=False),
    sa.Column('parent_id', sa.String(length=32), nullable=True),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('dm_notes', sa.Text(), nullable=False),
    sa.Column('tags_json', sa.JSON(), nullable=False),
    sa.Column('created_by', sa.String(length=10), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['locations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('locations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_locations_campaign_id'), ['campaign_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_locations_name'), ['name'], unique=False)

    op.create_table('monsters',
    sa.Column('campaign_id', sa.String(length=32), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('cr', sa.String(length=10), nullable=False),
    sa.Column('stat_block_json', sa.JSON(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('source', sa.String(length=10), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('monsters', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_monsters_campaign_id'), ['campaign_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_monsters_name'), ['name'], unique=False)

    op.create_table('quests',
    sa.Column('campaign_id', sa.String(length=32), nullable=False),
    sa.Column('scene_id', sa.String(length=32), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('dm_notes', sa.Text(), nullable=False),
    sa.Column('objectives_json', sa.JSON(), nullable=False),
    sa.Column('rewards_json', sa.JSON(), nullable=False),
    sa.Column('created_by', sa.String(length=10), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('quests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_quests_campaign_id'), ['campaign_id'], unique=False)

    op.create_table('summaries',
    sa.Column('campaign_id', sa.String(length=32), nullable=False),
    sa.Column('scope', sa.String(length=10), nullable=False),
    sa.Column('ref_id', sa.String(length=32), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('model', sa.String(length=120), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('summaries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_summaries_campaign_id'), ['campaign_id'], unique=False)

    op.create_table('world_events',
    sa.Column('campaign_id', sa.String(length=32), nullable=False),
    sa.Column('scene_id', sa.String(length=32), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('entity_refs_json', sa.JSON(), nullable=False),
    sa.Column('world_visibility', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('world_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_world_events_campaign_id'), ['campaign_id'], unique=False)

    op.create_table('chunks',
    sa.Column('document_id', sa.String(length=32), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('page_start', sa.Integer(), nullable=False),
    sa.Column('page_end', sa.Integer(), nullable=False),
    sa.Column('section_path', sa.String(length=500), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chunks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chunks_document_id'), ['document_id'], unique=False)

    op.create_table('inventory_entries',
    sa.Column('item_id', sa.String(length=32), nullable=False),
    sa.Column('owner_type', sa.String(length=12), nullable=False),
    sa.Column('owner_id', sa.String(length=32), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('equipped', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('inventory_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_inventory_entries_item_id'), ['item_id'], unique=False)
        batch_op.create_index('ix_inventory_owner', ['owner_type', 'owner_id'], unique=False)

    op.create_table('npcs',
    sa.Column('campaign_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('role', sa.String(length=120), nullable=False),
    sa.Column('disposition', sa.String(length=40), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('secrets', sa.Text(), nullable=False),
    sa.Column('location_id', sa.String(length=32), nullable=True),
    sa.Column('faction_id', sa.String(length=32), nullable=True),
    sa.Column('present_in_scene_id', sa.String(length=32), nullable=True),
    sa.Column('stat_block_json', sa.JSON(), nullable=True),
    sa.Column('hp_current', sa.Integer(), nullable=True),
    sa.Column('conditions_json', sa.JSON(), nullable=False),
    sa.Column('aliases_json', sa.JSON(), nullable=False),
    sa.Column('created_by', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.ForeignKeyConstraint(['faction_id'], ['factions.id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('npcs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_npcs_campaign_id'), ['campaign_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_npcs_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_npcs_present_in_scene_id'), ['present_in_scene_id'], unique=False)

    op.create_table('scenes',
    sa.Column('campaign_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('kind', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('dm_mode', sa.String(length=10), nullable=False),
    sa.Column('location_id', sa.String(length=32), nullable=True),
    sa.Column('party_json', sa.JSON(), nullable=False),
    sa.Column('dm_notes', sa.Text(), nullable=False),
    sa.Column('scratch_json', sa.JSON(), nullable=False),
    sa.Column('time_note', sa.String(length=200), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('summary_upto_seq', sa.Integer(), nullable=False),
    sa.Column('last_world_event_seen', sa.String(length=32), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('scenes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scenes_campaign_id'), ['campaign_id'], unique=False)

    op.create_table('ai_turns',
    sa.Column('scene_id', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('trigger_message_id', sa.String(length=32), nullable=True),
    sa.Column('steps_json', sa.JSON(), nullable=False),
    sa.Column('token_usage_json', sa.JSON(), nullable=False),
    sa.Column('model', sa.String(length=120), nullable=False),
    sa.Column('error', sa.Text(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['scene_id'], ['scenes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ai_turns', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_turns_scene_id'), ['scene_id'], unique=False)

    op.create_table('combat_encounters',
    sa.Column('scene_id', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('round', sa.Integer(), nullable=False),
    sa.Column('active_combatant_id', sa.String(length=32), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['scene_id'], ['scenes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('combat_encounters', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_combat_encounters_scene_id'), ['scene_id'], unique=False)

    op.create_table('messages',
    sa.Column('scene_id', sa.String(length=32), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('author_type', sa.String(length=10), nullable=False),
    sa.Column('author_user_id', sa.String(length=32), nullable=True),
    sa.Column('character_id', sa.String(length=32), nullable=True),
    sa.Column('kind', sa.String(length=12), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('payload_json', sa.JSON(), nullable=False),
    sa.Column('visibility', sa.String(length=10), nullable=False),
    sa.Column('struck', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['author_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ),
    sa.ForeignKeyConstraint(['scene_id'], ['scenes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scene_id', 'seq')
    )
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_messages_scene_id'), ['scene_id'], unique=False)

    op.create_table('pending_approvals',
    sa.Column('campaign_id', sa.String(length=32), nullable=False),
    sa.Column('scene_id', sa.String(length=32), nullable=False),
    sa.Column('kind', sa.String(length=12), nullable=False),
    sa.Column('payload_json', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('resolved_by', sa.String(length=32), nullable=True),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.ForeignKeyConstraint(['resolved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['scene_id'], ['scenes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pending_approvals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pending_approvals_campaign_id'), ['campaign_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pending_approvals_scene_id'), ['scene_id'], unique=False)

    op.create_table('tool_call_log',
    sa.Column('scene_id', sa.String(length=32), nullable=False),
    sa.Column('ai_turn_id', sa.String(length=32), nullable=True),
    sa.Column('message_id', sa.String(length=32), nullable=True),
    sa.Column('call_id', sa.String(length=64), nullable=False),
    sa.Column('tool', sa.String(length=60), nullable=False),
    sa.Column('args_json', sa.JSON(), nullable=False),
    sa.Column('result_json', sa.JSON(), nullable=False),
    sa.Column('inverse_patch_json', sa.JSON(), nullable=False),
    sa.Column('reverted', sa.Boolean(), nullable=False),
    sa.Column('approved_by', sa.String(length=32), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['scene_id'], ['scenes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ai_turn_id', 'call_id')
    )
    with op.batch_alter_table('tool_call_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tool_call_log_ai_turn_id'), ['ai_turn_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tool_call_log_scene_id'), ['scene_id'], unique=False)

    op.create_table('combatants',
    sa.Column('encounter_id', sa.String(length=32), nullable=False),
    sa.Column('ref_type', sa.String(length=12), nullable=False),
    sa.Column('ref_id', sa.String(length=32), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('initiative', sa.Integer(), nullable=False),
    sa.Column('hp_current', sa.Integer(), nullable=True),
    sa.Column('hp_max', sa.Integer(), nullable=True),
    sa.Column('ac', sa.Integer(), nullable=True),
    sa.Column('conditions_json', sa.JSON(), nullable=False),
    sa.Column('stat_block_json', sa.JSON(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('defeated', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['encounter_id'], ['combat_encounters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('combatants', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_combatants_encounter_id'), ['encounter_id'], unique=False)

    op.create_table('dice_rolls',
    sa.Column('scene_id', sa.String(length=32), nullable=False),
    sa.Column('message_id', sa.String(length=32), nullable=True),
    sa.Column('roller_user_id', sa.String(length=32), nullable=True),
    sa.Column('character_id', sa.String(length=32), nullable=True),
    sa.Column('roller_name', sa.String(length=120), nullable=False),
    sa.Column('expression', sa.String(length=60), nullable=False),
    sa.Column('rolls_json', sa.JSON(), nullable=False),
    sa.Column('modifier', sa.Integer(), nullable=False),
    sa.Column('total', sa.Integer(), nullable=False),
    sa.Column('purpose', sa.String(length=20), nullable=False),
    sa.Column('detail_json', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ),
    sa.ForeignKeyConstraint(['roller_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['scene_id'], ['scenes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('dice_rolls', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dice_rolls_scene_id'), ['scene_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dice_rolls', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dice_rolls_scene_id'))

    op.drop_table('dice_rolls')
    with op.batch_alter_table('combatants', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_combatants_encounter_id'))

    op.drop_table('combatants')
    with op.batch_alter_table('tool_call_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tool_call_log_scene_id'))
        batch_op.drop_index(batch_op.f('ix_tool_call_log_ai_turn_id'))

    op.drop_table('tool_call_log')
    with op.batch_alter_table('pending_approvals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pending_approvals_scene_id'))
        batch_op.drop_index(batch_op.f('ix_pending_approvals_campaign_id'))

    op.drop_table('pending_approvals')
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_messages_scene_id'))

    op.drop_table('messages')
    with op.batch_alter_table('combat_encounters', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_combat_encounters_scene_id'))

    op.drop_table('combat_encounters')
    with op.batch_alter_table('ai_turns', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_turns_scene_id'))

    op.drop_table('ai_turns')
    with op.batch_alter_table('scenes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scenes_campaign_id'))

    op.drop_table('scenes')
    with op.batch_alter_table('npcs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_npcs_present_in_scene_id'))
        batch_op.drop_index(batch_op.f('ix_npcs_name'))
        batch_op.drop_index(batch_op.f('ix_npcs_campaign_id'))

    op.drop_table('npcs')
    with op.batch_alter_table('inventory_entries', schema=None) as batch_op:
        batch_op.drop_index('ix_inventory_owner')
        batch_op.drop_index(batch_op.f('ix_inventory_entries_item_id'))

    op.drop_table('inventory_entries')
    with op.batch_alter_table('chunks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chunks_document_id'))

    op.drop_table('chunks')
    with op.batch_alter_table('world_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_world_events_campaign_id'))

    op.drop_table('world_events')
    with op.batch_alter_table('summaries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_summaries_campaign_id'))

    op.drop_table('summaries')
    with op.batch_alter_table('quests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_quests_campaign_id'))

    op.drop_table('quests')
    with op.batch_alter_table('monsters', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_monsters_name'))
        batch_op.drop_index(batch_op.f('ix_monsters_campaign_id'))

    op.drop_table('monsters')
    with op.batch_alter_table('locations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_locations_name'))
        batch_op.drop_index(batch_op.f('ix_locations_campaign_id'))

    op.drop_table('locations')
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_items_name'))
        batch_op.drop_index(batch_op.f('ix_items_campaign_id'))

    op.drop_table('items')
    with op.batch_alter_table('factions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_factions_name'))
        batch_op.drop_index(batch_op.f('ix_factions_campaign_id'))

    op.drop_table('factions')
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_documents_campaign_id'))

    op.drop_table('documents')
    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_characters_user_id'))
        batch_op.drop_index(batch_op.f('ix_characters_campaign_id'))

    op.drop_table('characters')
    with op.batch_alter_table('campaign_members', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_campaign_members_user_id'))
        batch_op.drop_index(batch_op.f('ix_campaign_members_campaign_id'))

    op.drop_table('campaign_members')
    with op.batch_alter_table('campaigns', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_campaigns_owner_id'))
        batch_op.drop_index(batch_op.f('ix_campaigns_invite_code'))

    op.drop_table('campaigns')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('srd_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_srd_entries_slug'))
        batch_op.drop_index(batch_op.f('ix_srd_entries_name'))
        batch_op.drop_index(batch_op.f('ix_srd_entries_kind'))

    op.drop_table('srd_entries')
    op.drop_table('embedding_config')
    with op.batch_alter_table('app_settings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_app_settings_key'))

    op.drop_table('app_settings')
    # ### end Alembic commands ###
